version: '3.7'

services:
  mssql:
    build:
      context: ./MSSQL
      dockerfile: Dockerfile
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./MSSQL/data:/var/opt/mssql